"""Extract the keyboard layout from the official positions.xml and emit a
JavaScript module for the frontend (SVG/3D keyboard rendering).

Only entries with a non-zero rect are real keys.
"""
import json
import re
import sys

SRC = r"C:\Program Files (x86)\AULA\F3001 三模机械键盘\positions.xml"
OUT_JS = r"d:\Project\OpenALUA\src\keyboard-layout.js"

PATTERN = re.compile(
    r'<pos\s+rect="([^"]+)"\s+va="([^"]+)"\s+id="(\d+)"\s+name="([^"]+)"'
)


def main():
    sys.stdout.reconfigure(encoding="utf-8")
    text = open(SRC, encoding="utf-8", errors="replace").read()

    keys = []
    for m in PATTERN.finditer(text):
        rect, _va, kid, name = m.groups()
        parts = [p.strip() for p in rect.split(",")]
        if len(parts) != 4:
            continue
        try:
            x, y, w, h = (int(p) for p in parts)
        except ValueError:
            continue
        if w <= 0 or h <= 0:
            continue  # placeholder row (numpad / indicators not present on this board)
        keys.append({"x": x, "y": y, "w": w, "h": h, "id": int(kid), "n": name})

    if not keys:
        raise SystemExit("no keys parsed")

    max_x = max(k["x"] + k["w"] for k in keys)
    max_y = max(k["y"] + k["h"] for k in keys)
    min_x = min(k["x"] for k in keys)
    min_y = min(k["y"] for k in keys)

    # normalise to start at 0,0 and expose the bounding box
    for k in keys:
        k["x"] -= min_x
        k["y"] -= min_y
    box = {"w": max_x - min_x, "h": max_y - min_y}

    js = (
        "// Generated by tools/extract_layout.py from the vendor positions.xml\n"
        "// x/y/w/h are in the vendor's own coordinate space (1 unit ~ 1 px at 1x)\n"
        f"window.KEYBOARD_LAYOUT = {json.dumps(keys, ensure_ascii=False, separators=(',', ':'))};\n"
        f"window.KEYBOARD_BOX = {json.dumps(box)};\n"
    )
    open(OUT_JS, "w", encoding="utf-8").write(js)
    print(f"parsed {len(keys)} keys, box={box}")
    names = [k["n"] for k in keys]
    print("sample:", ", ".join(names[:18]))
    print("wrote", OUT_JS)


if __name__ == "__main__":
    main()
